# Generated by Django 3.1.2 on 2020-10-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20201009_0105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Options',
        ),
        migrations.AlterModelOptions(
            name='options',
            options={'verbose_name_plural': 'Options'},
        ),
    ]
