# Generated by Django 3.1.2 on 2020-10-09 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201009_0135'),
        ('questions', '0004_optionvotes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='optionvotes',
            unique_together={('user', 'question', 'option')},
        ),
    ]
