# Generated by Django 3.1.2 on 2020-10-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20201011_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='files',
        ),
    ]
