# Generated by Django 3.1.2 on 2020-10-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_remove_question_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('deleted', 'Deleted'), ('open', 'Open'), ('waiting', 'waiting')], default='waiting', max_length=50),
        ),
    ]
