# Generated by Django 3.1.2 on 2020-10-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20201028_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('deleted', 'Deleted'), ('open', 'Open'), ('waiting', 'waiting'), ('spammed', 'Spammed')], default='waiting', max_length=50),
        ),
    ]
