# Generated by Django 3.1.2 on 2020-10-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201008_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websites',
            old_name='name',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='websites',
            old_name='website',
            new_name='pair',
        ),
        migrations.AlterUniqueTogether(
            name='websites',
            unique_together={('key', 'pair')},
        ),
    ]
