# Generated by Django 3.1.2 on 2021-01-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '__first__'),
        ('accounts', '0002_remove_profile_myinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='MyInterest',
            field=models.ManyToManyField(blank=True, related_name='userInterests', to='questions.Keywords'),
        ),
    ]
