# Generated by Django 3.1.2 on 2021-01-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '__first__'),
        ('accounts', '0003_profile_myinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='MyInterest',
            field=models.ManyToManyField(blank=True, related_name='userInterests', to='questions.Category'),
        ),
    ]
