# Generated by Django 3.1.2 on 2020-10-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201009_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='websites',
        ),
        migrations.AddField(
            model_name='profile',
            name='websites',
            field=models.ManyToManyField(null=True, related_name='userWebsites', to='accounts.Websites'),
        ),
        migrations.AlterUniqueTogether(
            name='websites',
            unique_together={('user_id', 'key', 'pair')},
        ),
    ]
