# Generated by Django 3.1.2 on 2020-10-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201009_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='websites',
            field=models.ManyToManyField(blank=True, related_name='userWebsites', to='accounts.Websites'),
        ),
    ]
